### ISSUE TITLE
CSV file

### ISSUE THREAD

**Issue by ghost** [vnherdeiro/transfermarkt-scraping#1]
Does this script actually create a csv file? I was only able to print the output?

**Comment by vnherdeiro** [comment]
@ValJ10 I made a mistake when cleaning the code: I forgot to remove a `pickle` call while having removed the `import pickle` line. This was causing the program to crash before exporting the data to a csv file. It is fixed now, please `git pull` and try again.

**Comment by ghost** [comment]
this still doesnt work. When i use "python3 main.py", it doesnt create the csv file. Also when i try to print the array leaguedata, its empty.  Sorry for annoying you.

**Comment by vnherdeiro** [comment]
Could you elaborate by telling me if you get any warning messages or import errors? I must ask if you are sure to have all the dependencies, I am thinking about `BeautifulSoup4`, `urllib` and `requests`.

**Comment by ghost** [comment]
There no warning problem. It runs, it shows when the player is done. And i can print all of the player information. The problem is the file is never created. Do i have wait until the script scrape all of the leagues in the dictionary  to see the file?

**Comment by vnherdeiro** [comment]
Yes, the data is stored to disk **only** at the end.  You can reduce the number of leagues (variable `N_LEAGUES` in `main.py`) if you're in a rush =)

**Comment by ghost** [comment]
Thanks for helping me out.

**Comment by vnherdeiro** [comment]
No problem, it does take some time (~1 hour) to collect all the data, and this is why I shared the csv file. Do you have more questions? Otherwise I will close this issue.
